name: proto_checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  proto_checks:
    name: proto lint, breaking changes detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-action@v1
        with:
          lint: true
          breaking: true
          breaking_against: https://github.com/anveshthakurhl/protolint.git#branch=main
          pr_comment: true
