name: proto_checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  proto_checks:
    name: proto lint, breaking changes detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/anveshthakurhl/protolint.git#branch=main"
